### PR TITLE
little testing of pull request

### PR DESCRIPTION
**Pull request by CheWeiLiao**
as title

### CODE REVIEW

**Comment by chiya335** [comment]
you have no test case

**Comment by CheWeiLiao** [comment]
I think only change the title of the web page do not need to have test case. Am I right?

**Comment by chiya335** [comment]
If I reply you after six months, will you lose the passion to go on?

**Comment by MOHOAzure** [comment]
Are you developers going to restart the project?

I saw the title is changed, and a number '2' is appended.

**Pull request closed without merging**
